"""add role field to user

Revision ID: c073dea7a331
Revises: 985193728d21
Create Date: 2026-02-28 14:26:44.019136

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c073dea7a331"
down_revision: Union[str, Sequence[str], None] = "985193728d21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "user", sa.Column("role", sa.String(), nullable=False, server_default="user")
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "role")
    # ### end Alembic commands ###
